// <auto-generated />
using System;
using EyewearShop.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EyewearShop.Data.Migrations
{
    [DbContext(typeof(Prn222EyewearshopContext))]
    [Migration("20260109053843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EyewearShop.Data.Models.AfterSalesTaiNd", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    b.Property<int?>("ExchangeProductId")
                        .HasColumnType("int")
                        .HasColumnName("exchangeProductID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processedAt");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processedBy");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<decimal?>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refundAmount");

                    b.Property<string>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("requestStatus");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("requestType");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("requestedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolutionNotes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("RequestId")
                        .HasName("PK__AfterSal__E3C5DE516E658BA9");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProcessedBy");

                    b.ToTable("AfterSalesTaiND", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.CategoryTriCh", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoryName");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parentID");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__23CAF1F82FBC8D54");

                    b.HasIndex(new[] { "Slug" }, "UQ__Category__32DD1E4C987C5815")
                        .IsUnique()
                        .HasFilter("[slug] IS NOT NULL");

                    b.ToTable("CategoryTriCH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.CustomerSupportQuiTh", b =>
                {
                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    b.Property<string>("IssueType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("issueType");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staffID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("SupportId")
                        .HasName("PK__Customer__E6765E74F617EED8");

                    b.HasIndex("StaffId");

                    b.ToTable("CustomerSupportQuiTH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.LensServicePhuHn", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("serviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("CoatingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("coatingType");

                    b.Property<int>("LensTypeId")
                        .HasColumnType("int")
                        .HasColumnName("lensTypeID");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescriptionID");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("servicePrice");

                    b.HasKey("ServiceId")
                        .HasName("PK__LensServ__4550733F4A94C787");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("LensServicePhuHN", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderItemNamtmh", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescriptionID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unitPrice");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variantID");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__3724BD722EB7F15C");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItemNamtmh", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderNamtmh", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discountAmount");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("finalAmount");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("orderNumber");

                    b.Property<string>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("orderStatus");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("orderType");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("paymentStatus");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shippingAddress");

                    b.Property<decimal?>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("shippingFee");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("totalAmount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("OrderId")
                        .HasName("PK__OrderNam__0809337D8568EEE2");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "OrderNumber" }, "UQ__OrderNam__6296129FE3780149")
                        .IsUnique();

                    b.ToTable("OrderNamtmh", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderReviewQuiTh", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("ContactMethod")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contactMethod");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("CustomerContacted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("customerContacted");

                    b.Property<string>("IssueNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issueNote");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescriptionID");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reviewStatus");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reviewType");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewedAt");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staffID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("ReviewId")
                        .HasName("PK__OrderRev__2ECD6E24DC647161");

                    b.HasIndex("StaffId");

                    b.ToTable("OrderReviewQuiTH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.PrescriptionPhuHn", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    b.Property<bool>("IsCustomLens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isCustomLens");

                    b.Property<int?>("LeftEyeAxis")
                        .HasColumnType("int")
                        .HasColumnName("leftEyeAxis");

                    b.Property<decimal?>("LeftEyeCyl")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("leftEyeCyl");

                    b.Property<decimal?>("LeftEyeSph")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("leftEyeSph");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("orderItemID");

                    b.Property<decimal?>("PupillaryDistance")
                        .HasColumnType("decimal(4, 1)")
                        .HasColumnName("pupillaryDistance");

                    b.Property<int?>("RightEyeAxis")
                        .HasColumnType("int")
                        .HasColumnName("rightEyeAxis");

                    b.Property<decimal?>("RightEyeCyl")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("rightEyeCyl");

                    b.Property<decimal?>("RightEyeSph")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("rightEyeSph");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalPrice");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Prescrip__7920FDC4121888B2");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("PrescriptionPhuHN", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductColorTriCh", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("colorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("colorCode");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("colorName");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stockQuantity");

                    b.HasKey("ColorId")
                        .HasName("PK__ProductC__70A64C3DF233A12F");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColorTriCH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductImageTriCh", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("imageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("colorID");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("displayOrder");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageURL");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isPrimary");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.HasKey("ImageId")
                        .HasName("PK__ProductI__336E9B75390B8242");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImageTriCH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductReviewMiLtt", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isVerified");

                    b.Property<int?>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("likeCount");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("ReviewId")
                        .HasName("PK__ProductR__2ECD6E245C0781AD");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviewMiLTT", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductTriCh", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brand");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("dimensions");

                    b.Property<string>("FrameType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("frameType");

                    b.Property<string>("Material")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("material");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("productName");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stockQuantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ProductId")
                        .HasName("PK__ProductT__2D10D14A39D9516B");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Sku" }, "UQ__ProductT__DDDF4BE7E8CDACB7")
                        .IsUnique()
                        .HasFilter("[sku] IS NOT NULL");

                    b.ToTable("ProductTriCH", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductionSonKn", b =>
                {
                    b.Property<int>("ProductionSonKnid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductionSonKNId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionSonKnid"));

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("ExpectedFinishDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsUrgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("ProductionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ShipmentSonKnid")
                        .HasColumnType("int")
                        .HasColumnName("ShipmentSonKNId");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProductionSonKnid")
                        .HasName("PK__Producti__10BAB72022A4AF42");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "ShipmentSonKnid" }, "UQ__Producti__83D5390ECDAA73F4")
                        .IsUnique()
                        .HasFilter("[ShipmentSonKNId] IS NOT NULL");

                    b.ToTable("ProductionSonKN", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.RefundTaiNd", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refundID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("refundAmount");

                    b.Property<DateTime?>("RefundDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("refundDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("refundMethod");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transactionID");

                    b.HasKey("RefundId")
                        .HasName("PK__RefundTa__B21984EFADC39F00");

                    b.HasIndex("RequestId");

                    b.ToTable("RefundTaiND", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ReviewImageMiLtt", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("imageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imageURL");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("reviewID");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uploadedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ImageId")
                        .HasName("PK__ReviewIm__336E9B7594259719");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImageMiLTT", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ShipmentSonKn", b =>
                {
                    b.Property<int>("ShipmentSonKnid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShipmentSonKNId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentSonKnid"));

                    b.Property<DateOnly?>("DeliveredDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("ShippedDate")
                        .HasColumnType("date");

                    b.Property<string>("ShippingCompany")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShipmentSonKnid")
                        .HasName("PK__Shipment__83D5390FF93A66D2");

                    b.ToTable("ShipmentSonKN", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserAccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountId"));

                    b.Property<string>("ApplicationCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RequestCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserAccountId")
                        .HasName("PK__UserAcco__DA6C70BA081FDE0E");

                    b.HasIndex(new[] { "UserName" }, "UQ__UserAcco__C9F28456452386CA")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("EyewearShop.Data.Models.AfterSalesTaiNd", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.OrderNamtmh", "Order")
                        .WithMany("AfterSalesTaiNds")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_AfterSales_Order");

                    b.HasOne("EyewearShop.Data.Models.UserAccount", "ProcessedByNavigation")
                        .WithMany("AfterSalesTaiNds")
                        .HasForeignKey("ProcessedBy")
                        .HasConstraintName("FK_AfterSales_Staff");

                    b.Navigation("Order");

                    b.Navigation("ProcessedByNavigation");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.CustomerSupportQuiTh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.UserAccount", "Staff")
                        .WithMany("CustomerSupportQuiThs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerSupport_Staff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.LensServicePhuHn", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.PrescriptionPhuHn", "Prescription")
                        .WithMany("LensServicePhuHns")
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_LensService_Prescription");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderItemNamtmh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.OrderNamtmh", "Order")
                        .WithMany("OrderItemNamtmhs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItemNamtmh_Order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderNamtmh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.UserAccount", "Customer")
                        .WithMany("OrderNamtmhs")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderNamtmh_User");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderReviewQuiTh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.UserAccount", "Staff")
                        .WithMany("OrderReviewQuiThs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderReview_Staff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.PrescriptionPhuHn", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.OrderNamtmh", "Order")
                        .WithMany("PrescriptionPhuHns")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Order");

                    b.HasOne("EyewearShop.Data.Models.OrderItemNamtmh", "OrderItem")
                        .WithMany("PrescriptionPhuHns")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_OrderItem");

                    b.Navigation("Order");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductColorTriCh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.ProductTriCh", "Product")
                        .WithMany("ProductColorTriChes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductColor_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductImageTriCh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.ProductColorTriCh", "Color")
                        .WithMany("ProductImageTriChes")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK_ProductImage_ProductColor");

                    b.HasOne("EyewearShop.Data.Models.ProductTriCh", "Product")
                        .WithMany("ProductImageTriChes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductImageTriCH_ProductTriCH");

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductReviewMiLtt", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.OrderNamtmh", "Order")
                        .WithMany("ProductReviewMiLtts")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_review_order");

                    b.HasOne("EyewearShop.Data.Models.ProductTriCh", "Product")
                        .WithMany("ProductReviewMiLtts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_review_product");

                    b.HasOne("EyewearShop.Data.Models.UserAccount", "User")
                        .WithMany("ProductReviewMiLtts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_review_user");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductTriCh", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.CategoryTriCh", "Category")
                        .WithMany("ProductTriChes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_ProductTriCH_CategoryTriCH");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductionSonKn", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.UserAccount", "AssignedToNavigation")
                        .WithMany("ProductionSonKns")
                        .HasForeignKey("AssignedTo")
                        .IsRequired()
                        .HasConstraintName("FK_ProductionSonKN_Staff");

                    b.HasOne("EyewearShop.Data.Models.OrderNamtmh", "Order")
                        .WithMany("ProductionSonKns")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductionSonKN_Order");

                    b.HasOne("EyewearShop.Data.Models.ShipmentSonKn", "ShipmentSonKn")
                        .WithOne("ProductionSonKn")
                        .HasForeignKey("EyewearShop.Data.Models.ProductionSonKn", "ShipmentSonKnid")
                        .HasConstraintName("FK_ProductionSonKN_Shipment");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Order");

                    b.Navigation("ShipmentSonKn");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.RefundTaiNd", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.AfterSalesTaiNd", "Request")
                        .WithMany("RefundTaiNds")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Refund_AfterSales");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ReviewImageMiLtt", b =>
                {
                    b.HasOne("EyewearShop.Data.Models.ProductReviewMiLtt", "Review")
                        .WithMany("ReviewImageMiLtts")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_review");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.AfterSalesTaiNd", b =>
                {
                    b.Navigation("RefundTaiNds");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.CategoryTriCh", b =>
                {
                    b.Navigation("ProductTriChes");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderItemNamtmh", b =>
                {
                    b.Navigation("PrescriptionPhuHns");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.OrderNamtmh", b =>
                {
                    b.Navigation("AfterSalesTaiNds");

                    b.Navigation("OrderItemNamtmhs");

                    b.Navigation("PrescriptionPhuHns");

                    b.Navigation("ProductReviewMiLtts");

                    b.Navigation("ProductionSonKns");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.PrescriptionPhuHn", b =>
                {
                    b.Navigation("LensServicePhuHns");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductColorTriCh", b =>
                {
                    b.Navigation("ProductImageTriChes");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductReviewMiLtt", b =>
                {
                    b.Navigation("ReviewImageMiLtts");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ProductTriCh", b =>
                {
                    b.Navigation("ProductColorTriChes");

                    b.Navigation("ProductImageTriChes");

                    b.Navigation("ProductReviewMiLtts");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.ShipmentSonKn", b =>
                {
                    b.Navigation("ProductionSonKn");
                });

            modelBuilder.Entity("EyewearShop.Data.Models.UserAccount", b =>
                {
                    b.Navigation("AfterSalesTaiNds");

                    b.Navigation("CustomerSupportQuiThs");

                    b.Navigation("OrderNamtmhs");

                    b.Navigation("OrderReviewQuiThs");

                    b.Navigation("ProductReviewMiLtts");

                    b.Navigation("ProductionSonKns");
                });
#pragma warning restore 612, 618
        }
    }
}
